### PR TITLE
Fix `fetch_api()` function

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
This fixes some stuff that didn't quite work of #5.

### CODE REVIEW

**Comment by OPARA-PROSPER** [comment]
Better still what types of manipulations are you thinking of?

From my end, I think the response is overwhelming (to much), we could limit the amount to JSON returned.

**Comment by AlbertoPdRF** [comment]
What I mean by manipulating is indeed making the output presentable to the user. The idea of the previous PR (which this one is fixing) was just to get to fetch the dev.to API.

**Comment by Oghenebrume50** [comment]
That makes sense @AlbertoPdRF I had same question as @OPARA-PROSPER but yeah you are right, I tested it and echo spits it out anyway, so we can focus on manipulating the data for order purposes

**Comment by OPARA-PROSPER** [comment]
@Oghenebrume50 I don't experience that on my end

How did you run the script?

**Comment by AlbertoPdRF** [comment]
Right, for now I've been using it as a standalone script instead of a plugin, that's why that's happening to you @Oghenebrume50.

**Comment by OPARA-PROSPER** [comment]
I'll send in a commit for formatting the output.

Grep command `curl ... | json_pp` does the trick

**Comment by Oghenebrume50** [comment]
@AlbertoPdRF I figured it out you just have to remove the last line, I guess the idea is to use it as a Plugin eventually so testing on the fly is better

@OPARA-PROSPER check [this](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#adding-a-new-plugin)

**Comment by AlbertoPdRF** [comment]
Let's discuss that elsewhere, as it's quite off-topic here.

**Comment by Oghenebrume50** [comment]
So I would approve and we can worry about making this work properly as a plugin later, I would just do that locally for now :+1:

**Comment by AlbertoPdRF** [comment]
Sounds good!

**Pull request merged**
